# Generated by Django 2.2.2 on 2019-06-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emaillist',
        ),
    ]
